---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1unpw0594q6kl5fy9jh4d3anc6xtz0zyfm8sp5ynvk7zf24lps9lq8667gn
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1unpw0594q6kl5fy9jh4d3anc6xtz0zyfm8sp5ynvk7zf24lps9lq8667gn
